export const FETCH_USER = 'FETCH_USER';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const FETCH_SEASON = 'FETCH_SEASON';
//export const FETCH_DAYS = 'FETCH_DAYS';

export const START_NEW_SEASON = 'START_NEWSEASON';
export const NEW_SEASON_STEP_BACK = 'NEW_SEASON_STEP_BACK';
export const SET_TRAINING_PLAN = 'SET_TRAINING_PLAN';
export const SET_START_DATE = 'SET_STARTDATE';
export const FETCH_TRAINING_PLAN = 'FETCH_TRAINING_PLAN';
